Wwwision:
  Snippets:
    definitions: []
#      'someSnippet':
#        title: 'SomeSnippet Title'
#        defaultSource: 'Default source for "someSnippet" with {placeholder}.'
#        variableDefinitions:
#          'placeholder':
#            required: true
#            type: string
#            defaultValue: 'some default value'